# Generated by Django 4.2 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtractieTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('tip', models.CharField(max_length=255)),
                ('latitudine', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitudine', models.DecimalField(decimal_places=10, max_digits=19)),
                ('programVizitare', models.CharField(blank=True, default='', max_length=255)),
                ('tarif', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ratingMediu', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('imagineCopertaUrl', models.CharField(blank=True, default='', max_length=255)),
                ('curiozitate', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Atracție Turistică',
                'verbose_name_plural': 'Atracții Turistice',
                'db_table': 'atractie_turistica',
            },
        ),
    ]
