# Generated by Django 4.2 on 2026-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atractii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractieturistica',
            name='imagineCopertaUrl',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
