# Generated by Django 4.2 on 2026-03-17 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilizatori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatorbadge',
            name='dataObtinere',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notificare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField()),
                ('tip', models.CharField(choices=[('badge', 'Badge Nou'), ('recenzie', 'Status Recenzie'), ('admin', 'Mesaj Admin'), ('altul', 'Altul')], default='altul', max_length=20)),
                ('esteCitita', models.BooleanField(default=False)),
                ('dataCreare', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificari',
                'db_table': 'notificare',
                'ordering': ['-dataCreare'],
            },
        ),
    ]
