# Generated by Django 4.2 on 2026-02-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regiuni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctTraseu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Punct Traseu',
                'verbose_name_plural': 'Puncte Traseu',
                'db_table': 'punct_traseu',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Traseu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctStart', models.CharField(max_length=255)),
                ('punctSosire', models.CharField(max_length=255)),
                ('distantaKm', models.DecimalField(decimal_places=2, max_digits=19)),
                ('durataMin', models.IntegerField()),
                ('dataPlanificata', models.DateField(blank=True, null=True)),
                ('abatereMaxKm', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tip', models.CharField(blank=True, default='', max_length=255)),
                ('estePrestabilit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Traseu',
                'verbose_name_plural': 'Trasee',
                'db_table': 'traseu',
            },
        ),
        migrations.CreateModel(
            name='TraseuPreparatLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasee', to='regiuni.preparatlocal')),
                ('traseu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparate', to='trasee.traseu')),
            ],
            options={
                'verbose_name': 'Traseu - Preparat Local',
                'verbose_name_plural': 'Traseu - Preparate Locale',
                'db_table': 'traseu_preparat_local',
            },
        ),
        migrations.CreateModel(
            name='TraseuFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasee', to='regiuni.festival')),
                ('traseu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivaluri', to='trasee.traseu')),
            ],
            options={
                'verbose_name': 'Traseu - Festival',
                'verbose_name_plural': 'Traseu - Festivaluri',
                'db_table': 'traseu_festival',
            },
        ),
    ]
