# Generated by Django 4.2 on 2026-02-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atractii', '0001_initial'),
        ('trasee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traseu',
            name='utilizator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trasee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puncttraseu',
            name='atractie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puncte_traseu', to='atractii.atractieturistica'),
        ),
        migrations.AddField(
            model_name='puncttraseu',
            name='traseu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puncte', to='trasee.traseu'),
        ),
        migrations.AlterUniqueTogether(
            name='traseupreparatlocal',
            unique_together={('traseu', 'preparat')},
        ),
        migrations.AlterUniqueTogether(
            name='traseufestival',
            unique_together={('traseu', 'festival')},
        ),
    ]
