# Generated by Django 4.2 on 2026-02-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atractii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagineRecenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagineUrl', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Imagine Recenzie',
                'verbose_name_plural': 'Imagini Recenzii',
                'db_table': 'imagine_recenzie',
            },
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('nota', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='in_asteptare', max_length=255)),
                ('motivRespingere', models.CharField(blank=True, default='', max_length=255)),
                ('atractie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to='atractii.atractieturistica')),
            ],
            options={
                'verbose_name': 'Recenzie',
                'verbose_name_plural': 'Recenzii',
                'db_table': 'recenzie',
            },
        ),
    ]
