# Generated by Django 4.2 on 2026-02-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recenzii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzie',
            name='utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imaginerecenzie',
            name='recenzie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='recenzii.recenzie'),
        ),
    ]
