# Generated by Django 4.2 on 2026-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenzii', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imaginerecenzie',
            name='imagineUrl',
        ),
        migrations.AddField(
            model_name='imaginerecenzie',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='recenzii/'),
        ),
    ]
