# Generated by Django 4.2 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('dataStart', models.DateField()),
                ('dataEnd', models.DateField()),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivaluri',
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='PreparatLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('regiune', models.CharField(max_length=255)),
                ('imagineUrl', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Preparat Local',
                'verbose_name_plural': 'Preparate Locale',
                'db_table': 'preparat_local',
            },
        ),
    ]
